data:
  bom-drafts:
    - id: bom-1
      item-id: item-1
    - id: bom-2
      item-id: item-2
    - id: bom-3
      item-id: item-3
    - id: bom-4
      item-id: item-4
    - id: bom-5
      item-id: item-5
    - id: toothbrush-0
      item-id: toothbrush-0
    - id: toothbrush-01
      item-id: toothbrush-01
    - id: toothbrush-02
      item-id: toothbrush-02
    - id: toothbrush-03
      item-id: toothbrush-03
    - id: toothbrush-04
      item-id: toothbrush-04
    - id: toothbrush-05
      item-id: toothbrush-05
    - id: toothbrush-051
      item-id: toothbrush-051
    - id: toothbrush-052
      item-id: toothbrush-052
    - id: toothbrush-06
      item-id: toothbrush-06
    - id: toothbrush-061
      item-id: toothbrush-061
    - id: toothbrush-07
      item-id: toothbrush-07
    - id: toothbrush-071
      item-id: toothbrush-071
    - id: toothbrush-072
      item-id: toothbrush-072
    - id: toothbrush-073
      item-id: toothbrush-073
    - id: materail-paper-iv
      item-id: materail-paper-iv
    - id: materail-paper-sc
      item-id: materail-paper-sc
    - id: sk-k-e
      item-id: sk-k-e
    - id: material-pet-04t
      item-id: material-pet-04t

  bom-processes:
    - id: bom-2
      process-id: item-2-process-1
    - id: toothbrush-0
      process-id: toothbrush-0
    - id: toothbrush-05
      process-id: toothbrush-05
    - id: toothbrush-051
      process-id: toothbrush-051
    - id: toothbrush-052
      process-id: toothbrush-052
    - id: toothbrush-06
      process-id: toothbrush-06
    - id: toothbrush-061
      process-id: toothbrush-061
    - id: toothbrush-07
      process-id: toothbrush-07
    - id: toothbrush-071
      process-id: toothbrush-071
    - id: toothbrush-072
      process-id: toothbrush-072
    - id: toothbrush-073
      process-id: toothbrush-073

  bom-materials:
    - bom-id: bom-1
      material-id: bom-2
      quantity: 1
    - bom-id: bom-2
      material-id: bom-3
      quantity: 1
    - bom-id: bom-3
      material-id: bom-4
      quantity: 1
    - bom-id: bom-4
      material-id: bom-5
      quantity: 1
    - bom-id: toothbrush-0
      material-id: toothbrush-01
      quantity: 2
    - bom-id: toothbrush-0
      material-id: toothbrush-02
      quantity: 2
    - bom-id: toothbrush-0
      material-id: toothbrush-03
      quantity: 2
    - bom-id: toothbrush-0
      material-id: toothbrush-04
      quantity: 2
    - bom-id: toothbrush-0
      material-id: toothbrush-05
      quantity: 1
    - bom-id: toothbrush-0
      material-id: toothbrush-06
      quantity: 1
    - bom-id: toothbrush-0
      material-id: toothbrush-07
      quantity: 0.1
    - bom-id: toothbrush-05
      material-id: toothbrush-052
      quantity: 0.25
    - bom-id: toothbrush-052
      material-id: toothbrush-051
      quantity: 1
    - bom-id: toothbrush-051
      material-id: materail-paper-iv
      quantity: 1
      item-spec-id: materail-paper-iv-spec-1
    - bom-id: toothbrush-06
      material-id: toothbrush-061
      quantity: 1
    - bom-id: toothbrush-061
      material-id: material-pet-04t
      quantity: 0.4
    - bom-id: toothbrush-07
      material-id: toothbrush-073
      quantity: 1
    - bom-id: toothbrush-072
      material-id: toothbrush-071
      quantity: 1
    - bom-id: toothbrush-072
      material-id: sk-k-e
      item-spec-id: sk-k-e-spec-1
      quantity: 1
    - bom-id: toothbrush-071
      material-id: materail-paper-sc
      item-spec-id: materail-paper-sc-spec-1
      quantity: 1

  bom-determines:
    - id: bom-5
    - id: bom-4
    - id: bom-3
    - id: bom-2
    - id: bom-1
    - id: materail-paper-sc
    - id: materail-paper-iv
    - id: sk-k-e
    - id: toothbrush-071
    - id: toothbrush-072
    - id: toothbrush-073
    - id: toothbrush-07
    - id: toothbrush-061
    - id: toothbrush-06
    - id: toothbrush-051
    - id: toothbrush-052
    - id: toothbrush-05
    - id: toothbrush-0
