data:
  bom-drafts:
    - id: bom-1
      item-id: item-1
    - id: bom-2
      item-id: item-2
    - id: bom-3
      item-id: item-3
    - id: bom-4
      item-id: item-4
    - id: bom-5
      item-id: item-5

  bom-processes:
    - id: bom-2
      process-id: item-2-process-1

  bom-materials:
    - bom-id: bom-1
      material-id: bom-2
      item-spec-id: item-2-spec-1
      quantity: 1
    - bom-id: bom-2
      material-id: bom-3
      quantity: 1
    - bom-id: bom-3
      material-id: bom-4
      quantity: 1
    - bom-id: bom-4
      material-id: bom-5
      quantity: 1

  bom-determines:
    - id: bom-5
    - id: bom-4
    - id: bom-3
    - id: bom-2
    - id: bom-1
